billeterie/urls.py
from django.urls import path

from billeterie import views
from billeterie.views import *

app_name = "billeterie"
urlpatterns = [

    path('', views.IndexView.as_view(), name='index'),

    path('no_places_remaining/', views.NoPlacesView.as_view(), name='no_places_remaining'),
    path('search_list/', views.SearchListView.as_view(), name='search_list'),
    path('already_register/', views.AlreadyRegisterView.as_view(), name='already_register'),
    path('register/', views.RegisterView.as_view(), name='register'),

    path('persons/', views.PersonsView.as_view(), name='persons'),

    path('events/', views.EventsView.as_view(), name='events'),
    path('create_event/', views.upload_event, name='create_event'),
    path('events/<int:event_id>', views.event, name='event'),
    path('events/<int:event_id>/delete', views.event_deleted, name='event_deleted'),
    path('events/<int:event_id>/modified', views.event_modified, name='event_modified'),
    path('events/<int:event_id>/add_member', views.event_add_member, name='event_add_member'),
    path('events/<int:event_id>/add_staff', views.event_add_staff, name='event_add_staff'),
    path('events/<int:event_id>/delete_staff', views.event_delete_staff, name='event_delete_staff'),
    path('events/<int:event_id>/validate', views.event_validate, name='event_validate'),
    path('events/<int:event_id>/refuse', views.event_refuse, name='event_refuse'),

    path('associations/', views.AssociationsView.as_view(), name='associations'),
    path('association_exist/', views.AssociationExistView.as_view(), name='association_exist'),
    path('create_association/', views.upload_association, name='create_association'),
    path('associations/<int:association_id>', views.association, name='association'),
    path('associations/<int:association_id>/delete', views.association_deleted, name='association_deleted'),
    path('associations/<int:association_id>/modified', views.association_modified, name='association_modified'),
    path('associations/<int:association_id>/add_member', views.association_add_member, name='association_add_member'),
    path('associations/<int:association_id>/delete_member', views.association_delete_member, name='association_delete_member'),

    path('profile/<int:user_id>/modified', views.profile_modified, name='profile_modified'),
    path('profile/<str:validation_code>', views.profile_billet, name='profile_billet'),
    path('profile/<int:event_id>/search', views.search_billet, name='search_billet'),
    path('profile/<int:event_id>/list', views.list_billet, name='list_billet'),

    ###########
    path('login/', views.login, name='login'),
    path('logged/', views.logged, name='logged'),
    path('profile/', views.profile, name='profile'),
    path('registration/', views.registration, name='registration'),
    path('accounts/birthdate', views.person, name='birthdate'),

    path('client-autocomplete/', ClientAutocomplete.as_view(), name='client-autocomplete'),

    path('epita/', views.epita, name="epita"),

    path('process_payment/', views.process_payment, name="process_payment"),
    path('payment_done/', views.payment_done, name="payment_done"),
    path('payment_canceled', views.payment_canceled, name="payment_canceled"),
]

yakastar/urls.py
from django.conf import settings
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.views.static import serve

from social_django.urls import urlpatterns as social_django_urls
from django.contrib.auth.views import logout

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include((social_django_urls, 'social'), namespace='social')),

    path('', include('billeterie.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path(r'logout/', logout, {'next_page': '/'}, name="logout"),

    path('paypal/', include('paypal.standard.ipn.urls')),
]

urlpatterns += [
        url(r'^media/(?P<path>.*)', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]

billeterie/models.py
from django.contrib.auth.forms import UserCreationForm
from django.db import models
from django.contrib.auth.models import User, Group

# Create your models here.
from django import forms
from django.forms import Form
from django.utils import timezone


class Person(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, default=None)
    birth_date = models.DateField(default=timezone.now)
    is_intern = models.BooleanField(default=None)

    def __str__(self):
        return self.user.username


class Association(models.Model):
    name = models.CharField(max_length=128)
    chef = models.ForeignKey(Person, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return self.name


class AssociationMember(models.Model):
    user = models.ForeignKey(Person, on_delete=models.CASCADE, default=None)
    association = models.ForeignKey(Association, on_delete=models.CASCADE, default=None)
    grade = models.CharField(max_length=64)

    def __str__(self):
        return self.association.name + ": " + self.user.__str__()


class Event(models.Model):
    title = models.CharField(max_length=64)
    description = models.TextField(default="Entrez une description ...")

    begin_date = models.DateTimeField(default=timezone.now)
    end_date = models.DateTimeField(default=timezone.now)
    end_inscription = models.DateTimeField(default=timezone.now)

    place = models.CharField(max_length=128, default="Epita")
    image = models.ImageField(upload_to='images', null=True, blank=True)

    association = models.ForeignKey(Association, on_delete=models.CASCADE)

    max_intern = models.PositiveIntegerField(default=0)
    max_extern = models.PositiveIntegerField(default=0)
    price_intern = models.PositiveIntegerField(default=0)
    price_extern = models.PositiveIntegerField(default=0)

    display_remaining_places = models.BooleanField(default=True)

    INFO_TYPE_CHOICES = [
        ('VALIDATED', 'Validé et ouvert'),
        ('CLOSED', 'Inscriptions terminés'),
        ('WAITING', 'En attente de validation'),
        ('TERMINATED', 'Evénement terminé'),
        ('REFUSED', 'Refusé'),
    ]

    info_type = models.CharField(max_length=10, choices=INFO_TYPE_CHOICES, default=None)
    creator = models.ForeignKey(Person, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return self.title


class EventMember(models.Model):
    user = models.ForeignKey(Person, on_delete=models.CASCADE, default=None)
    event = models.ForeignKey(Event, on_delete=models.CASCADE, default=None)
    validation_code = models.CharField(max_length=6)

    def __str__(self):
        return self.event.__str__() + ": " + self.user.__str__()


class EventStaff(models.Model):
    user = models.ForeignKey(Person, on_delete=models.CASCADE, default=None)
    event = models.ForeignKey(Event, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return self.event.__str__() + ": " + self.user.__str__()


class DateForm(Form):
    birth_date = forms.DateField()

    class Meta:
        fields = ('birth_date',)


class RegistrationForm(UserCreationForm):
    username = forms.CharField(label='Pseudo', max_length=30, required=True, help_text='Veuillez entrer un pseudo')
    first_name = forms.CharField(label='Prénom', max_length=30, required=True, help_text='Veuillez entrer votre prénom')
    last_name = forms.CharField(label='Nom', max_length=30, required=True, help_text='Veuillez entrer votre nom')
    email = forms.EmailField(max_length=254, required=True, help_text='Veuillez entrer votre addresse email,')
    password1 = forms.CharField(label='Mot de passe', min_length=8, max_length=64, widget=forms.PasswordInput(),
                                required=True, help_text='Entrer un mot de passe avec au moins 8 caractères. Le mot '
                                                         'de passe ne doit pas être similaire a votre pseudo.')
    password2 = forms.CharField(label='Confirmation de mot de passe', min_length=8, max_length=64,
                                widget=forms.PasswordInput(), required=True, help_text='Entrer le même mot de passe.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2',)

billeterie/templates/association_add_member.html
{% extends "base.html" %}

{% block title %}
Association - Billeterie Epita
{% endblock %}

{% load static %}

{% block body %}
<h2>Ajout d'un membre dans une association</h2>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Ajouter">
</form>
<input type="submit" value="Annuler" onclick="window.location='/associations/' + {{ association_id }};"/>

<script type="text/javascript" src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>
{{ form.media }}
{% endblock %}

billeterie/templates/base.html
<!DOCTYPE HTML>
<html>
    {% load static %}
    <head>
        <meta charset="utf-8">
        <title>{% block title %}{% endblock %}</title>

        <!-- css -->
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

        {% block css %}{% endblock %}
    </head>

    <!-- content -->
    <body>

        <!-- header -->
        <header class="container-fluid col-12 header">
            <div class="row">
                <div class="col-1 offset-1 img-container">
                    <a href="/epita">
                        <img src="{% static 'img/logo_epita.png' %}" alt="Logo Epita">
                    </a>
                </div>

                <div class="col-1">
                    <a href="/" class="home">Billeterie</a>
                </div>

                <div class="col-2 offset-4">
                    <form class="searchbar" id="searchform" action="{% url 'billeterie:search_list' %}" method="get" accept-charset="utf-8">
                        <input name="q" type="search" class="placeholder" id="search" value="Rechercher..."/>
                    </form>

                </div>

                <div class="col-3 account">
                    {% if user.is_authenticated %}
                    <a href="/profile" class="connexion">Mon compte</a>
                    |
                    <a href="/logout" class="connexion">Déconnexion</a>
                    {% else %}
                    <a href="/accounts/login" class="connexion">S'identifier</a>
                    |
                    <a href="/registration" class="connexion">S'inscrire</a>
                    {% endif %}
                </div>
            </div>
        </header>
        <!-- end header -->

        <!-- navigation -->
        <section class="container-fluid col-8 offset-2 navigation">
                <nav class="menu">
                    {% block links %}
                    <a href="/">Accueil</a>
                    <a href="/events">Liste des événements</a>
                    <a href="/persons">Liste des membres</a>
                    <a href="/associations">Liste des associations</a>
                    {% endblock %}
                </nav>
        </section>
        <!-- end navigation -->

        <!-- body -->
        <section class="container-fluid col-8 offset-2 body">
            {% block body %}{% endblock %}
        </section>
        <!-- end body -->

        <!-- footer -->
        <footer class="container-fluid col-12 footer">
            {% block footer %}{% endblock %}
        </footer>
        <!-- end footer -->

        <!-- script -->
        <script src="{% static 'js/script.js' %}"></script>
        {% block script %}{% endblock %}
    </body>
</html>

billeterie/templates/billet_list.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %}
Billets - Billeterie Epita
{% endblock %}

{% load billeterie_extras %}

{%block body %}
<h3>Liste des inscrits pour l'événement: {{ name }}</h3>
{% if members %}
    <table cellpadding="10">
        <tr>
            <td><b>Prénom</b></td>
            <td><b>Nom</b></td>
            <td><b>Code de validation</b></td>
        </tr>
        {% for member in members %}
        <tr>
            <td>{{ member.user.user.first_name }}</td>
            <td>{{ member.user.user.last_name }}</td>
            <td>{{ member.validation_code }}</td>
        </tr>
        {% endfor %}
    </table>
{% endif %}

{% endblock %}

billeterie/templates/create_event.html
{% extends "base.html" %}

{% block title %}
Création d'événement - Billeterie Epita
{% endblock %}

{% block body %}
<h2>Creation d'evenement</h2>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Créer">
</form>
<input type="submit" value="Annuler" onclick="window.location='/';"/>
{% endblock %}

billeterie/templates/event.html
{% extends "base.html" %}

{% block title %}
Evénement - Billeterie Epita
{% endblock %}

{% load billeterie_extras %}

{% block body %}
<h2>{{ event.title }}</h2>
{% if event.description == "Entrez une description ..." %}
    <p>Il n'y a pas de description pour cet événement.</p>
{% else %}
    <p class="description">{{ event.description }}</p>
{% endif %}
<p><strong>Date de début: </strong>{{ event.begin_date }}</p>
<p><strong>Date de fin: </strong>{{ event.end_date }}</p>
<p><strong>Date de fin de l'inscription: </strong>{{ event.end_inscription }}</p>
<p><strong>Lieu: </strong>{{ event.place }}</p>
{% if event.image %}
    <img class="img_event" src="{{ event.image.url }}">
{% endif %}
<p><strong>Association: </strong>{{ event.association }}</p>
<p><strong>Places maximum pour des personnes externes: </strong>{{ event.max_extern }}</p>
<p><strong>Places maximum pour des personnes internes: </strong>{{ event.max_intern }}</p>
<p><strong>Prix d'une place externe: </strong>{{ event.price_extern }} €</p>
<p><strong>Prix d'une place interne: </strong>{{ event.price_intern }} €</p>
{% if event.display_remaining_places %}
    <p><strong>Places restantes pour des personnes externes: </strong>{{ rpe }}</p>
    <p><strong>Places restantes pour des personnes internes: </strong>{{ rpi }}</p>
{% endif %}

{% if event.info_type == 'WAITING' %}
    <p><strong>L'événement est en attente de validation les inscriptions ne sont pas encore ouvertes</strong></p>
{% elif event.info_type == 'REFUSED' %}
    <p><strong>L'événement a été refusé, il n'auras donc pas lieu, désolé :(</strong></p>
{% elif event.info_type == 'CLOSED' %}
    <p><strong>Les inscriptions à l'événement sont terminées, désolé :(</strong></p>
{% elif event.info_type == 'TERMINATED' %}
    <p><strong>L'événement est terminé, désolé :(</strong></p>
{% endif %}

<div class="buttons">
    {% if event.info_type == 'VALIDATED' %}
        <form action="{% url 'billeterie:event_add_member' event.id %}" method="post">
            {% csrf_token %}
            <input type="submit" value="S'inscrire"/>
        </form>
    {% endif %}

    {% if request.user|has_perm_creator_event:event.id and event.info_type == 'VALIDATED' %}
        <form action="{% url 'billeterie:event_add_staff' event.id %}" method="get">
            {% csrf_token %}
            <input type="submit" value="Ajouter un staff"/>
        </form>
    {% endif %}

    {% if request.user|has_perm_creator_event:event.id and event.info_type == 'VALIDATED' %}
        <form action="{% url 'billeterie:event_delete_staff' event.id %}" method="get">
            {% csrf_token %}
            <input type="submit" value="Supprimer un staff"/>
        </form>
    {% endif %}

    {% if request.user|has_perm_creator_event:event.id and event.info_type != 'TERMINATED' %}
        <form action="{% url 'billeterie:event_modified' event.id %}" method="get">
            {% csrf_token %}
            <input type="submit" value="Modification"/>
        </form>
    {% endif %}

    {% if request.user|has_perm_chef:event.association %}
        <form action="{% url 'billeterie:event_deleted' event.id %}" method="post">
            {% csrf_token %}
            <input type="submit" value="Suppression"/>
        </form>
    {% endif %}

    {% if event.info_type == "WAITING" and request.user|has_perm_chef:event.association %}
        <form action="{% url 'billeterie:event_validate' event.id %}" method="get">
            {% csrf_token %}
            <input type="submit" value="Valider"/>
        </form>
    {% endif %}

    {% if event.info_type == "WAITING" and request.user|has_perm_chef:event.association %}
        <form action="{% url 'billeterie:event_refuse' event.id %}" method="get">
            {% csrf_token %}
            <input type="submit" value="Refuser"/>
        </form>
    {% endif %}
</div>
{% endblock %}

billeterie/templates/event_add_member.html
{% extends "base.html" %}

{% block title %}
Evénement - Billeterie Epita
{% endblock %}

{% load static %}

{% block body %}
<h2>Ajout d'un membre dans un événement</h2>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Ajouter">
</form>
<input type="submit" value="Annuler" onclick="window.location='/events/' + {{ event_id }};"/>

<script type="text/javascript" src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>
{{ form.media }}
{% endblock %}

billeterie/templates/events.html
{% extends "base.html" %}
{% load billeterie_extras %}

{% block title %}
Evénements - Billeterie
{% endblock %}

{% block body %}
<h2>Liste des evenements</h2>
{% if request.user|has_perm_member_asso %}
    <h4><a href="/create_event">Créer un événement</a></h4>
{% endif %}
{% if event_list %}
    <table cellpadding="10">
        <tr>
            <td><b>Nom</b></td>
            <td><b>Status</b></td>
            <td><b>Association</b></td>
            <td><b>Créateur</b></td>
        </tr>
        
        {% for event in event_list %}
        <tr>
            <td><a href="{{ event.id }}">{{ event.title }}</a></td>
            {% for t, m in event.INFO_TYPE_CHOICES %}
                {% if t == event.info_type %}
                        <td>{{ m }}</td>
                {% endif %}
            {% endfor %}
            <td>{{ event.association.name }}</td>
            <td>{{ event.creator.user.username }}</td>
        </tr>
        {% endfor %}
    </table>
{% else %}
    <p>Pas d'evenements.</p>
{% endif %}

{% include "pagination.html" %}
{% endblock %}

billeterie/templates/index.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %}
Accueil - Billeterie Epita
{% endblock %}

{% block css %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">
<link rel="stylesheet" type="text/css" href="{% static 'cal/css/styles.css' %}">
{% endblock %}

{% block body %}
<div class="global_slider">
    <div id="myCarousel" class="carousel slide slider_self" data-ride="carousel">

        <ol class="carousel-indicators">
            {% for event in events %}
                {% if forloop.counter0 == 0 %}
                    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                {% else %}
                    <li data-target="#myCarousel" data-slide-to="{{ forloop.counter0 }}"></li>
                {% endif %}
            {% endfor %}
        </ol>

        <div class="carousel-inner box_sliders" role="listbox">
            {% for event in events %}
                {% if forloop.counter == 1 %}
                    <div class="item active box_slider">
                {% else %}
                    <div class="item box_slider">
                {% endif %}
                        {% if event.image %}
                            <img src="{{ event.image.url }}" alt="Image" class="img_slider">
                        {% else %}
                            <img src="{% static 'img/logo_epita.png' %}" alt="Image" class="img_slider">
                        {% endif %}
                        <div class="carousel-caption text_slider">
                            <h3>{{ event.title }}</h3>
                            <p>{{ event.description }}</p>
                            {% for t, m in event.INFO_TYPE_CHOICES %}
                                {% if t == event.info_type %}
                                    <p>{{ m }}</p>
                                {% endif %}
                            {% endfor %}
                        </div>
                    </div>
            {% endfor %}
        </div>

        <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>

        </div>
    </div>
</div>

<div class="block">
    <div class="clearfix">
        <a class="btn btn-info left" href="{% url 'billeterie:index' %}?{{ prev_month }}"> Mois Précédent </a>
        <a class="btn btn-info right" href="{% url 'billeterie:index' %}?{{ next_month }}"> Mois Suivant </a>
    </div>
        {{ calendar }}
</div>

<div>
    <img src="{% static 'img/red.png' %}"> Staff de l'événement
    <img src="{% static 'img/green.png' %}"> Inscrits à l'événement
    <img src="{% static 'img/maroon.png' %}"> Créateur de l'événement
    <img src="{% static 'img/purple.png' %}"> Chef de l'association pour l'événement
    <img src="{% static 'img/blue.png' %}"> Autres événements
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

{% endblock %}

billeterie/templates/login.html
{% extends "base.html" %}

{% block title %}
Connexion/Inscription - Billeterie Epita
{% endblock %}

{% block body %}
<h1>Page de connexion/inscription</h1>
<input type="submit" value="Connexion Cri" onclick="window.location='{% url 'social:begin' backend='epita' %}';"/>
<input type="submit" value="Se connecter" onclick="window.location='/accounts/login';"/>
<input type="submit" value="S'inscrire" onclick="window.location='/registration/';"/>
{% endblock %}

billeterie/templates/pagination.html
{% load billeterie_extras %}
<nav aria-label="Page navigation" class="pagination">
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page=1" tabindex="-1">Premier</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1">Précédent</a>
            </li>
        {% endif %}
        {% for i in page_obj.paginator.page_range %}
            {% if i > page_obj.number|add:-5 and i < page_obj.number|add:5 %}
                <li class="page-item {% if i == page_obj.number %}active{% endif %}">
                    <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                </li>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" tabindex="-1">Dernier</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1">Suivant</a>
            </li>
        {% endif %}
    </ul>
</nav>

billeterie/templates/payment_done.html
{% extends "base.html" %}

{% block title %}
Paiement validé - Billeterie
{% endblock %}

{% block body %}
<h2>Le paiement a bien été validé.</h2>
{% endblock %}

billeterie/templates/payment_failed.html
{% extends "base.html" %}

{% block title %}
Paiement refusé - Billeterie
{% endblock %}

{% block body %}
<h2>Le paiement a été refusé.</h2>
{% endblock %}

billeterie/templates/profile.html
{% extends "base.html" %}

{% block title %}
Profil - Billeterie Epita
{% endblock %}

{% block body %}
<h2>Votre profil</h2>
<p>Pseudo: {{ user.username }}</p>
<p>Prénom: {{ user.first_name }}</p>
<p>Nom: {{ user.last_name }}</p>
<p>Email: {{ user.email }}</p>
<p>Date de naissance: {{ person.birth_date }}</p>
{% if events %}
<p><strong>Evénéments: </strong></p>
<ul>
{% for event in events %}
    <li class="indent">{{ event.event.title }} <a href="{{ event.validation_code }}">Voir mon billet</a></li>
{% endfor %}
</ul>
{% endif %}
{% if chefs %}
<p><strong>Chef d'associations: </strong></p>
<ul>
{% for chef in chefs %}
    <li class="indent">{{ chef.name }}</li>
{% endfor %}
</ul>
{% endif %}
{% if associations %}
<p><strong>Associations: </strong></p>
<ul>
{% for association in associations %}
    <li class="indent">{{ association.association.name }}</li>
{% endfor %}
</ul>
{% endif %}
{% if staffs %}
    <p><strong>Staff: </strong></p>
    <ul>
    {% for staff in staffs %}
        <li class="indent">{{ staff.event.title }}
            <a href="{{ staff.event.id }}/search">Rechercher un billet</a>
            <a href="{{ staff.event.id }}/list">Lister les billets</a>
        </li>
    {% endfor %}
    </ul>
{% endif %}
{% if eventschef %}
    <p><strong>Chef des événements: </strong></p>
    <ul>
    {% for event in eventschef %}
        <li class="indent">{{ event.title }}
            <a href="{{ event.id }}/search">Rechercher un billet</a>
            <a href="{{ event.id }}/list">Lister les billets</a>
        </li>
    {% endfor %}
    </ul>
{% endif %}

<form action="{% url 'billeterie:profile_modified' user.id %}" method="get">
    {% csrf_token %}
    <input type="submit" value="Modification"/>
</form>
<input type="submit" value="Se déconnecter" onclick="window.location='/logout';"/>
{% endblock %}

billeterie/templates/search.html
{% extends "base.html" %}
{% load billeterie_extras %}

{% block title %}
Recherche - Billeterie
{% endblock %}

{% block body %}
<h2>Résultats de la recherche</h2>

{% if events or associations %}
    <table cellpadding="10" class="double_table">
        <tr>
            <td><b>Event</b></td>
        </tr>
        {% for event in events %}
            <tr>
                <td><a href="/events/{{ event.id }}">{{ event.title }}</a></td>
            </tr>
        {% endfor %}
        
    </table>
    <table cellpadding="10" class="double_table">
        <tr>
            <td><b>Association</b></td>
        </tr>
        {% for association in associations %}
            <tr>
                <td><a href="/associations/{{ association.id }}">{{ association.name }}</a></td>
            </tr>
        {% endfor %}
    </table>
{% else %}
    <p>Pas de recherche trouvée.</p>
{% endif %}

{% include "pagination.html" %}
{% endblock %}